(part "MICROFJ-60035-TSV-TR"
    (packageRef "BGA36C100P6X6_613X613X67")
    (interface
        (port "A1" (symbPinId 1) (portName "CATHODE_1") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "NO_CONNECT_1") (portType INOUT))
        (port "A3" (symbPinId 3) (portName "NO_CONNECT_2") (portType INOUT))
        (port "A4" (symbPinId 4) (portName "NO_CONNECT_3") (portType INOUT))
        (port "A5" (symbPinId 5) (portName "NO_CONNECT_4") (portType INOUT))
        (port "A6" (symbPinId 6) (portName "NO_CONNECT_5") (portType INOUT))
        (port "B1" (symbPinId 7) (portName "NO_CONNECT_6") (portType INOUT))
        (port "B2" (symbPinId 8) (portName "NO_CONNECT_7") (portType INOUT))
        (port "B3" (symbPinId 9) (portName "NO_CONNECT_8") (portType INOUT))
        (port "B4" (symbPinId 10) (portName "NO_CONNECT_9") (portType INOUT))
        (port "B5" (symbPinId 11) (portName "NO_CONNECT_10") (portType INOUT))
        (port "B6" (symbPinId 12) (portName "NO_CONNECT_11") (portType INOUT))
        (port "C1" (symbPinId 13) (portName "ANODE_1") (portType INOUT))
        (port "C2" (symbPinId 14) (portName "NO_CONNECT_12") (portType INOUT))
        (port "C3" (symbPinId 15) (portName "NO_CONNECT_13") (portType INOUT))
        (port "C4" (symbPinId 16) (portName "NO_CONNECT_14") (portType INOUT))
        (port "C5" (symbPinId 17) (portName "NO_CONNECT_15") (portType INOUT))
        (port "C6" (symbPinId 18) (portName "FAST_OUTPUT_1") (portType INOUT))
        (port "D1" (symbPinId 19) (portName "ANODE_2") (portType INOUT))
        (port "D2" (symbPinId 20) (portName "NO_CONNECT_16") (portType INOUT))
        (port "D3" (symbPinId 21) (portName "NO_CONNECT_17") (portType INOUT))
        (port "D4" (symbPinId 22) (portName "NO_CONNECT_18") (portType INOUT))
        (port "D5" (symbPinId 23) (portName "NO_CONNECT_19") (portType INOUT))
        (port "D6" (symbPinId 24) (portName "FAST_OUTPUT_2") (portType INOUT))
        (port "E1" (symbPinId 25) (portName "NO_CONNECT_20") (portType INOUT))
        (port "E2" (symbPinId 26) (portName "NO_CONNECT_21") (portType INOUT))
        (port "E3" (symbPinId 27) (portName "NO_CONNECT_22") (portType INOUT))
        (port "E4" (symbPinId 28) (portName "NO_CONNECT_23") (portType INOUT))
        (port "E5" (symbPinId 29) (portName "NO_CONNECT_24") (portType INOUT))
        (port "E6" (symbPinId 30) (portName "NO_CONNECT_25") (portType INOUT))
        (port "F1" (symbPinId 31) (portName "NO_CONNECT_26") (portType INOUT))
        (port "F2" (symbPinId 32) (portName "NO_CONNECT_27") (portType INOUT))
        (port "F3" (symbPinId 33) (portName "NO_CONNECT_28") (portType INOUT))
        (port "F4" (symbPinId 34) (portName "NO_CONNECT_29") (portType INOUT))
        (port "F5" (symbPinId 35) (portName "NO_CONNECT_30") (portType INOUT))
        (port "F6" (symbPinId 36) (portName "CATHODE_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "863-MFJ60035TSVTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/MICROFJ-60035-TSV-TR?qs=byeeYqUIh0MKhzx4oC65Mg%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "MICROFJ-60035-TSV-TR")
    (property "Description" "High-density microcells; Optimized for high-performance timing applications, such as ToF-PET; Ultra-low dark count rates of 50 kHz/mm2 typical; J-Series sensors feature ON Semiconductor's unique 'fast output' terminal; Exceptional breakdown voltage uniformity of +/-250 mV; Temperature stability of 21.5 mV/C; 3 mm, 4 mm and 6 mm sensor sizes; Available in a reflow solder compatible TSV chip-scale package; Bias voltage of <30 V")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/MICROJ-SERIES-D.PDF")
    (property "symbolName1" "MICROFJ-60035-TSV-TR")
)
