(part "AFBR-S4N44P014M"
    (packageRef "AFBRS4N44P014M")
    (interface
        (port "A1" (symbPinId 1) (portName "CATHODE_1") (portType INOUT))
        (port "A3" (symbPinId 2) (portName "CATHODE_2") (portType INOUT))
        (port "B2" (symbPinId 3) (portName "ANODE") (portType INOUT))
        (port "C1" (symbPinId 4) (portName "CATHODE_3") (portType INOUT))
        (port "C3" (symbPinId 5) (portName "CATHODE_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "630-AFBR-S4N44P014M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Broadcom-Avago/AFBR-S4N44P014M?qs=OcgtsXO%252B3gvCU3dbtxthow%3D%3D")
    (property "Manufacturer_Name" "Avago Technologies")
    (property "Manufacturer_Part_Number" "AFBR-S4N44P014M")
    (property "Description" "Photodiode 420nm Single Element")
    (property "Datasheet_Link" "https://docs.broadcom.com/doc/AFBR-S4N44P014M-NUV-MT-Silicon-Photomultiplier")
    (property "symbolName1" "AFBR-S4N44P014M")
)
