[env:weact_mini_h750vbtx]
platform = ststm32
board = weact_mini_h750vbtx
framework = arduino

; Change upload protocol to dfu
upload_protocol = dfu

build_flags =
    -Iinclude

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library